In [2]:
#Data cleaning for Data Science using Python
#https://www.youtube.com/watch?v=NeJKaolLQqU&t=1283s

In [3]:
import pandas as pd
import numpy as np

In [4]:
#load messy data file
df = pd.read_csv("marketing_campaign_data_messy.csv")
print(f"Loaded Dataset: {df.shape[0]} rows, {df.shape[1]} columns" )

Loaded Dataset: 2020 rows, 12 columns

In [5]:
#print(df.shape)

In [6]:
df.head()

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Clicks,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24 00:00:00,2023-12-13,TikTok,16795,197,$102.82,20.0,Y,NaN,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06 00:00:00,2023-05-12,Facebook,1860,30,24.33,1.0,0,NaN,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13 00:00:00,2023-12-20,Email,77820,843,1323.39,51.0,No,NaN,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,NaN,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22 00:00:00,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,NaN,FA

In [7]:
# SETP 1 : Header Cleaning(rename)
print(df.columns.tolist())
# all columns to lowercase and replace space with '_'
df.columns = df.columns.str.strip().str.lower().str.replace(' ','_')

print("After")
print(df.columns.tolist())

[' Campaign_ID ', 'Campaign_Name', 'Start_Date', 'End_Date', 'Channel', 'Impressions', 'Clicks ', 'Spend', 'Conversions', 'Active', 'Clicks', 'Campaign_Tag']
After
['campaign_id', 'campaign_name', 'start_date', 'end_date', 'channel', 'impressions', 'clicks', 'spend', 'conversions', 'active', 'clicks', 'campaign_tag']

In [8]:
#Step 2 : Type Conversion and Currency Cleaning
values_with_sign_dollar = df['spend'].astype(str).str.contains(r'\$')

print(df.loc[values_with_sign_dollar,['campaign_id','spend']].head(3))

#replace and character not a digit, dot or minus with nothing, only numbers allowed
df['spend'] = df['spend'].astype(str).str.replace(r'[^\d._]','',regex= True)
#convert to numeric
df['spend'] = pd.to_numeric(df['spend'])

print("After Fix")

print(df.loc[values_with_sign_dollar,['campaign_id','spend']].head(3))

   campaign_id     spend
0    CMP-00001   $102.82
21   CMP-00022   $2428.4
22   CMP-00023  $4726.22
After Fix
   campaign_id    spend
0    CMP-00001   102.82
21   CMP-00022  2428.40
22   CMP-00023  4726.22

In [9]:
#STEP 3: CATEGORICAL TYPOS (FUZZY LOGIC)

#check for unique names in channel column
print(df['channel'].unique())

#replace with misspelled ones
cleanup_map = {
    'Tik_Tok' : 'TikTok',
    'Facebok' : 'Facebook',
    'Insta_gram' : 'Instagram',
    'Gogle' : 'Google Ads',
    'E-mail' : 'Email',
    'N/A ' : np.nan # handling ghost values
}

#channel column replace with cleanup_map
df['channel'] = df['channel'].replace(cleanup_map)

print("AfterFix")
print(df['channel'].unique())

['TikTok' 'Facebook' 'Email' 'Instagram' 'Google Ads' 'E-mail' nan 'Gogle'
 'Tik_Tok' 'Facebok' 'Insta_gram']
AfterFix
['TikTok' 'Facebook' 'Email' 'Instagram' 'Google Ads' nan]

In [10]:
#Step4 : Handling mixed booleans
print(df['active'].unique())

bool_map = {
    'Y' : 'True',
    'Yes': 'True',
    '1':'True',
    1 : 'True',
    
    '0' : 'False',
    'No' : 'False',
    0 :'False'
    
}

df['active'] = df['active'].map(bool_map).fillna(False).astype(bool)

print("After Fixed")
print(df['active'].unique())

['Y' '0' 'No' 'True' 'Yes' '1' 'False']
After Fixed
[ True False]

In [11]:
#Step 5 : Date Parsing
print(df['start_date'].dtype)

df['start_date'] = pd.to_datetime(df['start_date'], errors = 'coerce')
df['end_date'] = pd.to_datetime(df['end_date'], dayfirst= True, errors = 'coerce')

print("After Fix")
print(df['start_date'].dtype)

object
After Fix
datetime64[ns]

/var/folders/yd/yct4r0zs52s19qtz96_4r0j80000gn/T/ipykernel_1240/3018262570.py:5: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['end_date'] = pd.to_datetime(df['end_date'], dayfirst= True, errors = 'coerce')

In [12]:
df

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,clicks,campaign_tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,True,NaN,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,True,NaN,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,True,NaN,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,NaT,2023-11-03,TikTok,55886,2019,2180.38,135.0,False,NaN,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,True,NaN,FA
...,...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31,2023-11-13,TikTok,30592,586,503.95,77.0,True,NaN,TI
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01,2023-09-26,Google Ads,20097,897,1641.00,162.0,True,NaN,GO
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09,2023-02-21,Instagram,33254,1117,883.82,214.0,True,NaN,IN
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30,2023-04-27,Facebook,68728,2960,4198.50,591.0,True,NaN,FA
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26,2023-07-09,Email,96402,1090,1315.59,66.0,True,NaN,EM

In [13]:
#remove duplicate columns
df = df.loc[:, ~df.columns.duplicated()]
df

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,campaign_tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,True,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,True,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,True,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,NaT,2023-11-03,TikTok,55886,2019,2180.38,135.0,False,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,True,FA
...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31,2023-11-13,TikTok,30592,586,503.95,77.0,True,TI
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01,2023-09-26,Google Ads,20097,897,1641.00,162.0,True,GO
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09,2023-02-21,Instagram,33254,1117,883.82,214.0,True,IN
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30,2023-04-27,Facebook,68728,2960,4198.50,591.0,True,FA
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26,2023-07-09,Email,96402,1090,1315.59,66.0,True,EM

In [15]:
#step 6 : Logical Intergrity vs Impressions
impossible_mask = df['clicks'] > df['impressions']
print(df.loc[impossible_mask,['campaign_id','impressions','clicks']].head(3))

# check for any values in clicks high than Impressions

Empty DataFrame
Columns: [campaign_id, impressions, clicks]
Index: []

In [16]:
#Step 7 : Logical Integrity (Time travel)
# to check any end date in the past compare to start date

time_travel_mask = df['end_date'] < df['start_date']
print(df.loc[time_travel_mask,['campaign_id','start_date','end_date']].head(3))

   campaign_id start_date   end_date
23   CMP-00024 2023-05-06 2023-05-01
54   CMP-00055 2023-09-01 2023-08-27
71   CMP-00072 2023-02-01 2023-01-27

In [18]:
df.loc[time_travel_mask,'end_date' ] = df.loc[time_travel_mask,'start_date' ] +pd.Timedelta(days = 30)

print("After Fix")

print(df.loc[time_travel_mask,['campaign_id','start_date','end_date']].head(3))

After Fix
   campaign_id start_date   end_date
23   CMP-00024 2023-05-06 2023-06-05
54   CMP-00055 2023-09-01 2023-10-01
71   CMP-00072 2023-02-01 2023-03-03

In [19]:
#Step 8: Handling Outliers (Winsorizing)
Q1 = df['spend'].quantile(0.25)
Q3 = df['spend'].quantile(0.75)

IQR = Q3 - Q1
upper_limit = Q3 + (3 * IQR)
outlier_mask = df['spend'] > upper_limit
print(df.loc[outlier_mask,['campaign_id','spend']].head(3))

print("FIX APPLIED")
df.loc[outlier_mask, 'spend'] = upper_limit
print(df.loc[outlier_mask,['campaign_id','spend']].head(3))

     campaign_id      spend
789    CMP-00790  500000.00
1443   CMP-01444    8921.51
1460   CMP-01461  500000.00
FIX APPLIED
     campaign_id      spend
789    CMP-00790  8576.8675
1443   CMP-01444  8576.8675
1460   CMP-01461  8576.8675

In [20]:
#Step 9 : String parsing

print(df['campaign_name'].head(3))

df['season'] = df['campaign_name'].str.extract(r'Q\d_([^_]+)_')

print("FIX APPLIED")

print(df[['campaign_name','season']].head(3))

0    Q4_Summer_CMP-00001
1    Q1_Launch_CMP-00002
2    Q3_Winter_CMP-00003
Name: campaign_name, dtype: object
FIX APPLIED
         campaign_name  season
0  Q4_Summer_CMP-00001  Summer
1  Q1_Launch_CMP-00002  Launch
2  Q3_Winter_CMP-00003  Winter